import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'



import Navbar from "../components/Navbar";
import Hero from '../components/Hero';
import About from '../components/About';
import Services from '../components/Services';
import Expereince from '../components/Expereince';
import  Portfolio from '../components/Portfolio';
import Contact from "../components/Contact";
import Footer from "../components/Footer"
import Subscribe from "@/components/subscribe";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Navbar/>
       < Hero/>
       < About/>
       <Services/>
       <Expereince/>
     
       < Portfolio/>
      < Contact/>
    <Footer/>
    <Subscribe/>
        {children}
       
      </body>
    </html>
  );
}
